apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: courses
  namespace: argocd
spec:
  destination:
    namespace: courses
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/operrathor/courses-cd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true